### ISSUE TITLE
What does 'RGB' stand for?

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/FAQ#26]
Originally, the name RGB was chosen because the project started as a "better version of colored coins". Then, already during the few weeks into the research work with Peter Todd, in 2018, it diverged so much that it has nothing to do anymore with colored coins. But the name stuck.

**Comment by BitcoinErrorLog** [comment]
RGB is an additive color model in which **r**ed, **g**reen, and **b**lue light are added together in various ways to reproduce a broad array of colors. 

Since RGB is an established, well-known color spectrum that is both digitally expressible and human perceivable, it is an appropriate name for this RGB project, which aims to anchor human-perceivable abstractions using "colorations" of Bitcoin.

In this case, there is no special acronym definition for this project, but maybe one day someone will think of one!

**Comment by UkolovaOlga** [comment]
Added to the FAQ
